let currentModule=0,currentQ=null,currentScenario=null,examQs=[],diagStep=0;
let progress=JSON.parse(localStorage.getItem("giaV21")||'{"completed":[],"practice":{"a":0,"c":0},"scenarios":{"a":0,"c":0},"exams":[],"missed":{},"cats":{}}');
function save(){localStorage.setItem("giaV21",JSON.stringify(progress));ready();}
function pct(c,a){return a?Math.round(c/a*100):0}
function cat(category,correct){if(!progress.cats[category])progress.cats[category]={a:0,c:0};progress.cats[category].a++;if(correct)progress.cats[category].c++}
function miss(q){if(!progress.missed[q.id])progress.missed[q.id]={id:q.id,category:q.category,times:0,corrected:false};progress.missed[q.id].times++;progress.missed[q.id].corrected=false}
function corrected(q){if(progress.missed[q.id])progress.missed[q.id].corrected=true}
function readiness(){let m=progress.completed.length/MODULES.length*100,p=pct(progress.practice.c,progress.practice.a),s=pct(progress.scenarios.c,progress.scenarios.a),e=progress.exams.length?Math.max(...progress.exams):0;return Math.round(m*.20+p*.25+s*.25+e*.30)}
function label(x){return x>=95?"Exam Ready":x>=85?"Ready":x>=70?"Nearly Ready":"Not Ready"}
function ready(){let r=readiness();readyScore.textContent=r+"%";readyLabel.textContent=label(r)}
document.querySelectorAll(".tab").forEach(t=>t.onclick=()=>{document.querySelectorAll(".tab,.view").forEach(x=>x.classList.remove("active"));t.classList.add("active");document.getElementById(t.dataset.view).classList.add("active");if(t.dataset.view==="dashboard")dashboard();if(t.dataset.view==="missed")missedList();if(t.dataset.view==="diagnostic")diag()});
function renderModules(){moduleList.innerHTML="<h3>Modules</h3>";MODULES.forEach((m,i)=>{let b=document.createElement("button");b.className="moduleBtn"+(i===currentModule?" active":"")+(progress.completed.includes(m.id)?" complete":"");b.textContent=(i+1)+". "+m.title;b.onclick=()=>{currentModule=i;renderModule();renderModules()};moduleList.appendChild(b)})}
function renderModule(){let m=MODULES[currentModule];moduleContent.innerHTML=`<p class="eyebrow">Study Mode</p><h2>${currentModule+1}. ${m.title}</h2><p><strong>Objective:</strong> ${m.objective}</p>`+m.lessons.map(l=>`<div class="lesson"><h3>${l[0]}</h3><p>${l[1]}</p><p><strong>Memory Aid:</strong> ${l[2]}</p></div>`).join("")+`<div class="memory"><strong>Mastery Target:</strong> 85%+</div>`}
prev.onclick=()=>{currentModule=Math.max(0,currentModule-1);renderModule();renderModules()}
next.onclick=()=>{currentModule=Math.min(MODULES.length-1,currentModule+1);renderModule();renderModules()}
complete.onclick=()=>{let id=MODULES[currentModule].id;if(!progress.completed.includes(id))progress.completed.push(id);save();renderModules()}
practiceModule.innerHTML='<option value="all">All Modules</option>'+MODULES.map(m=>`<option value="${m.id}">${m.title}</option>`).join("");
newPractice.onclick=practice;
function qhtml(q,name){return `<div class="qcard"><p class="eyebrow">${q.id} · ${q.category}</p><h3>${q.q}</h3>${q.choices.map((c,i)=>`<label class="option"><input type="radio" name="${name}" value="${i}"> ${String.fromCharCode(65+i)}. ${c}</label>`).join("")}</div>`}
function practice(){let pool=practiceModule.value==="all"?QUESTIONS:QUESTIONS.filter(q=>q.module===practiceModule.value);currentQ=pool[Math.floor(Math.random()*pool.length)];practiceBox.innerHTML=qhtml(currentQ,"pans")+`<button id="checkP">Check Answer</button><div id="pfb"></div>`;checkP.onclick=()=>checkAnswer("pans",currentQ,pfb,true)}
function checkAnswer(name,q,fb,track){let ch=document.querySelector(`input[name="${name}"]:checked`);if(!ch){fb.innerHTML='<div class="feedback bad">Choose an answer first.</div>';return}let ok=Number(ch.value)===q.answer;if(track){progress.practice.a++;if(ok)progress.practice.c++;cat(q.category,ok);ok?corrected(q):miss(q);save()}fb.innerHTML=`<div class="feedback ${ok?"":"bad"}"><strong>${ok?"Correct":"Incorrect"}.</strong> ${q.explain}<br><strong>Memory Aid:</strong> ${q.memory}</div>`}
function missedList(){let arr=Object.values(progress.missed);if(!arr.length){missedBox.innerHTML="<p>No missed questions yet.</p>";return}missedBox.innerHTML=`<table><tr><th>ID</th><th>Category</th><th>Times</th><th>Status</th></tr>${arr.map(m=>`<tr><td>${m.id}</td><td>${m.category}</td><td>${m.times}</td><td>${m.corrected?"Corrected":"Needs Review"}</td></tr>`).join("")}</table>`}
reviewMissed.onclick=()=>{let ids=Object.values(progress.missed).filter(m=>!m.corrected).map(m=>m.id);if(!ids.length){missedBox.innerHTML="<p>No active missed questions.</p>";return}let q=QUESTIONS.find(q=>q.id===ids[Math.floor(Math.random()*ids.length)]);missedBox.innerHTML=qhtml(q,"mans")+`<button id="checkM">Check Review</button><div id="mfb"></div>`;checkM.onclick=()=>{let ch=document.querySelector('input[name="mans"]:checked');if(!ch){mfb.innerHTML='<div class="feedback bad">Choose an answer first.</div>';return}let ok=Number(ch.value)===q.answer;cat(q.category,ok);ok?corrected(q):miss(q);save();mfb.innerHTML=`<div class="feedback ${ok?"":"bad"}"><strong>${ok?"Corrected":"Still needs review"}.</strong> ${q.explain}</div>`}}
clearMissed.onclick=()=>{Object.keys(progress.missed).forEach(id=>{if(progress.missed[id].corrected)delete progress.missed[id]});save();missedList()}
startExam.onclick=()=>{examQs=[...QUESTIONS].sort(()=>Math.random()-.5).slice(0,Math.min(20,QUESTIONS.length));gradeExam.disabled=false;examBox.innerHTML=examQs.map((q,i)=>qhtml(q,"e"+i)).join("")}
gradeExam.onclick=()=>{let c=0,rev="";examQs.forEach((q,i)=>{let ch=document.querySelector(`input[name="e${i}"]:checked`),ok=ch&&Number(ch.value)===q.answer;if(ok)c++;else miss(q);cat(q.category,ok);rev+=`<div class="feedback ${ok?"":"bad"}"><strong>${q.id}:</strong> ${ok?"Correct":"Review"} — ${q.explain}</div>`});let sc=Math.round(c/examQs.length*100);progress.exams.push(sc);save();gradeExam.disabled=true;examBox.innerHTML=`<h3>Exam Score: ${sc}%</h3><p>${sc>=85?"Target met.":"Keep studying. Target is 85%+."}</p>`+rev}
newScenario.onclick=scenario;
function scenario(){currentScenario=SCENARIOS[Math.floor(Math.random()*SCENARIOS.length)];scenarioBox.innerHTML=`<div class="qcard"><p class="eyebrow">${currentScenario.id} · ${currentScenario.category}</p><h3>${currentScenario.title}</h3><p>${currentScenario.prompt}</p>${currentScenario.choices.map((c,i)=>`<label class="option"><input type="radio" name="sans" value="${i}"> ${String.fromCharCode(65+i)}. ${c}</label>`).join("")}</div><button id="checkS">Check Decision</button><div id="sfb"></div>`;checkS.onclick=()=>{let ch=document.querySelector('input[name="sans"]:checked');if(!ch){sfb.innerHTML='<div class="feedback bad">Choose an answer first.</div>';return}let ok=Number(ch.value)===currentScenario.answer;progress.scenarios.a++;if(ok)progress.scenarios.c++;cat(currentScenario.category,ok);save();sfb.innerHTML=`<div class="feedback ${ok?"":"bad"}"><strong>${ok?"Good decision":"Review this decision"}.</strong> ${currentScenario.explain}</div>`}}
function diag(){let steps=[["Yellow turf: is it uniform or patchy?",["Uniform","Patchy"]],["Uniform: consider nitrogen, iron, drought, recent rainfall, or broad water stress.",null],["Patchy: check irrigation coverage, disease pattern, insects, shade, compaction, or localized damage.",null]];let s=steps[diagStep];diagBox.innerHTML=`<div class="qcard"><h3>${s[0]}</h3>${s[1]?s[1].map((x,i)=>`<button onclick="diagStep=${i+1};diag()">${x}</button>`).join(" "):'<button onclick="diagStep=0;diag()">Restart</button>'}</div>`}
function dashboard(){let r=readiness(),mp=Math.round(progress.completed.length/MODULES.length*100),pp=pct(progress.practice.c,progress.practice.a),sp=pct(progress.scenarios.c,progress.scenarios.a),be=progress.exams.length?Math.max(...progress.exams):0,active=Object.values(progress.missed).filter(m=>!m.corrected).length;let rows=Object.entries(progress.cats).map(([k,v])=>`<tr><td>${k}</td><td>${v.c}/${v.a}</td><td>${pct(v.c,v.a)}%</td></tr>`).join("");let weak=Object.entries(progress.cats).filter(([k,v])=>v.a>=2&&pct(v.c,v.a)<85).map(([k])=>k).join(", ")||"No weak area identified yet.";dashBox.innerHTML=`<div class="grid"><div class="metric"><strong>${r}%</strong>Readiness Score™<br>${label(r)}</div><div class="metric"><strong>${mp}%</strong>Module Completion</div><div class="metric"><strong>${pp}%</strong>Practice Accuracy</div><div class="metric"><strong>${sp}%</strong>Scenario Accuracy</div><div class="metric"><strong>${be}%</strong>Best Exam</div><div class="metric"><strong>${active}</strong>Active Misses</div></div><h3>Weak Area Analyzer™</h3>${rows?`<table><tr><th>Category</th><th>Correct</th><th>Accuracy</th></tr>${rows}</table>`:"<p>No category data yet.</p>"}<h3>Recommended Study Focus</h3><p>${weak}</p>`}
reset.onclick=()=>{if(confirm("Reset all local progress?")){localStorage.removeItem("giaV21");location.reload()}}
renderModules();renderModule();practice();scenario();ready();
